# coding: utf-8

"""
    

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401

from typing import Any, Dict, Optional

from pydantic import BaseModel, constr, Field, StrictStr, validator


class CreateWorkflowRequest(BaseModel):
    """
    CreateWorkflowRequest
    """

    name: Optional[StrictStr] = Field(
        None,
        description="The name of the workflow. This field has been deprecated in favor of the `config.name` field.",
    )
    project_id: constr(strict=True) = Field(
        ..., description="The project ID that this workflow should belong to."
    )
    config: Optional[Dict[str, Any]] = Field(
        None,
        description="The workflow config object. See production documentation for more information on the structure of this field.",
    )
    config_text: Optional[StrictStr] = Field(
        None, description="The workflow config as a YAML string."
    )
    runner_mode: Optional[StrictStr] = Field(
        None,
        description="The runner mode of the workflow. Can be `cloud` or `hybrid`. Some projects may require workflows to run in a specific mode.",
    )
    __properties = ["name", "project_id", "config", "config_text", "runner_mode"]

    @validator("project_id")
    def project_id_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^proj_.*$", value):
            raise ValueError(r"must validate the regular expression /^proj_.*$/")
        return value

    @validator("runner_mode")
    def runner_mode_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in (
            "RUNNER_MODE_UNSET",
            "RUNNER_MODE_CLOUD",
            "RUNNER_MODE_HYBRID",
            "RUNNER_MODE_INVALID",
        ):
            raise ValueError(
                "must be one of enum values ('RUNNER_MODE_UNSET', 'RUNNER_MODE_CLOUD', 'RUNNER_MODE_HYBRID', 'RUNNER_MODE_INVALID')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateWorkflowRequest:
        """Create an instance of CreateWorkflowRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateWorkflowRequest:
        """Create an instance of CreateWorkflowRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateWorkflowRequest.parse_obj(obj)

        _obj = CreateWorkflowRequest.parse_obj(
            {
                "name": obj.get("name"),
                "project_id": obj.get("project_id"),
                "config": obj.get("config"),
                "config_text": obj.get("config_text"),
                "runner_mode": obj.get("runner_mode"),
            }
        )
        return _obj
