name: pm wheel build

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run the workflow on'
        required: true
        default: 'main'
        type: string

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.branch || github.ref }}
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
    - name: Build wheel
      run: |
        pip install wheel
        python setup.py sdist bdist_wheel