name: Run Test Suite

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install
      run: make setup
    - name: Lint
      run: make lint
    - name: Unit Tests
      run: make test
    - name: Run blueprints
      run: make blueprints
#     - name: Integration Tests
#       env:
#         GRETEL_TEST_API_KEY: ${{ secrets.GRETEL_TEST_API_KEY }}
#       run: make test-int
    - uses: 8398a7/action-slack@v2
      with:
        status: ${{ job.status }}
        author_name: unit tests
        only_mention_fail: here
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
